[package]
edition = "2018"
name = "tokio-futures"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "*"
tokio = {version = "1", features = ["full"]}
random-seed-future = { path= "../random-seed-future" }